import React from 'react';
import MenuItem from 'material-ui/MenuItem';


export default [
    <MenuItem key='Agriculture' value={'Agriculture'} primaryText="Agriculture"/>,
    <MenuItem key='Anthropology' value={'Anthropology'} primaryText="Anthropology"/>,
    <MenuItem key='Architecture' value={'Architecture'} primaryText="Architecture"/>,
    <MenuItem key='Biology and Biomedical' value={'Biology and Biomedical'} primaryText="Biology and Biomedical"/>,
    <MenuItem key='Business' value={'Business'} primaryText="Business"/>,
    <MenuItem key='Communications' value={'Communications'} primaryText="Communications"/>,
    <MenuItem key='Communications Tech' value={'Communications Tech'} primaryText="Communications Tech"/>,
    <MenuItem key='Computer Science' value={'Computer Science'} primaryText="Computer Science"/>,
    <MenuItem key='Construction' value={'Construction'} primaryText="Construction"/>,
    <MenuItem key='Culinary' value={'Culinary'} primaryText="Culinary"/>,
    <MenuItem key='Education' value={'Education'} primaryText="Education"/>,
    <MenuItem key='Engineering' value={'Engineering'} primaryText="Engineering"/>,
    <MenuItem key='Engineering Tech' value={'Engineering Tech'} primaryText="Engineering Tech"/>,
    <MenuItem key='English' value={'English'} primaryText="English"/>,
    <MenuItem key='Family & Consumer Sci' value={'Family & Consumer Sci'} primaryText="Family & Consumer Sci"/>,
    <MenuItem key='Health' value={'Health'} primaryText="Health"/>,
    <MenuItem key='History' value={'History'} primaryText="History"/>,
    <MenuItem key='Humanities' value={'Humanities'} primaryText="Humanities"/>,
    <MenuItem key='Law Enforcement' value={'Law Enforcement'} primaryText="Law Enforcement"/>,
    <MenuItem key='Legal Professions' value={'Legal Professions'} primaryText="Legal Professions"/>,
    <MenuItem key='Library Science' value={'Library Science'} primaryText="Library Science"/>,
    <MenuItem key='Linguistics' value={'Linguistics'} primaryText="Linguistics"/>,
    <MenuItem key='Mathematics' value={'Mathematics'} primaryText="Mathematics"/>,
    <MenuItem key='Mechanic & Repair Tech' value={'Mechanic & Repair Tech'} primaryText="Mechanic & Repair Tech"/>,
    <MenuItem key='Military Technologies' value={'Military Technologies'} primaryText="Military Technologies"/>,
    <MenuItem key='Multi/Interdisciplinary' value={'Multi/Interdisciplinary'} primaryText="Multi/Interdisciplinary"/>,
    <MenuItem key='Nat Resources & Conservation' value={'Nat Resources & Conservation'} primaryText="Nat Resources & Conservation"/>,
    <MenuItem key='Parks & Recreation' value={'Parks & Recreation'} primaryText="Parks & Recreation"/>,
    <MenuItem key='Philosophy & Religious' value={'Philosophy & Religious'} primaryText="Philosophy & Religious"/>,
    <MenuItem key='Physical Sciences' value={'Physical Sciences'} primaryText="Physical Sciences"/>,
    <MenuItem key='Precision Production' value={'Precision Production'} primaryText="Precision Production"/>,
    <MenuItem key='Psychology' value={'Psychology'} primaryText="Psychology"/>,
    <MenuItem key='pub_adm_soc_serv' value={'pub_adm_soc_serv'} primaryText="Social Services"/>,
    <MenuItem key='Science Technologies' value={'Science Technologies'} primaryText="Science Technologies"/>,
    <MenuItem key='Social Sciences' value={'Social Sciences'} primaryText="Social Sciences"/>,
    <MenuItem key='Theology & Religious Vocations' value={'Theology & Religious Vocations'} primaryText="Theology & Religious Vocations"/>,
    <MenuItem key='Transportation' value={'Transportation'} primaryText="Transportation"/>,
    <MenuItem key='Visual and Performing Arts' value={'Visual and Performing Arts'} primaryText="Visual and Performing Arts"/>
]
