import React from 'react';
import MenuItem from 'material-ui/MenuItem';


export default [
    <MenuItem key='argi' value={'english'} primaryText="Agriculture"/>,
    <MenuItem key='anthro' value={'anthropology'} primaryText="Anthropology"/>,
    <MenuItem key='arch' value={'architecture'} primaryText="Architecture"/>,
    <MenuItem key='biol_sci' value={'biol_sci'} primaryText="Biological Sciences"/>,
    <MenuItem key='bus_mktg_mgmt' value={'bus_mktg_mgmt'} primaryText="Business"/>,
    <MenuItem key='comm' value={'comm'} primaryText="Communications"/>,
    <MenuItem key='comm_tech' value={'comm_tech'} primaryText="Communications Tech"/>,
    <MenuItem key='comp_sci' value={'comp_sci'} primaryText="Computer Science"/>,
    <MenuItem key='construction' value={'construction'} primaryText="Construction"/>,
    <MenuItem key='culinary' value={'culinary'} primaryText="Culinary"/>,
    <MenuItem key='edu' value={'edu'} primaryText="Education"/>,
    <MenuItem key='engi' value={'engi'} primaryText="Engineering"/>,
    <MenuItem key='engi_tech' value={'engi_tech'} primaryText="Engineering Technology"/>,
    <MenuItem key='english' value={'english'} primaryText="English"/>,
    <MenuItem key='fam_cnsmr_sci' value={'fam_cnsmr_sci'} primaryText="Family & Consumer Sci"/>,
    <MenuItem key='health' value={'health'} primaryText="Health"/>,
    <MenuItem key='history' value={'history'} primaryText="History"/>,
    <MenuItem key='humanities' value={'humanities'} primaryText="Humanities"/>,
    <MenuItem key='law_enf_secur' value={'law_enf_secur'} primaryText="Law Enforcement"/>,
    <MenuItem key='legal' value={'legal'} primaryText="Law"/>,
    <MenuItem key='library_sci' value={'library_sci'} primaryText="Library Science"/>,
    <MenuItem key='linguistics' value={'linguistics'} primaryText="Linguistics"/>,
    <MenuItem key='math' value={'math'} primaryText="Mathematics"/>,
    <MenuItem key='mechanic' value={'mechanic'} primaryText="Mechanical Engineering"/>,
    <MenuItem key='military' value={'military'} primaryText="Military"/>,
    <MenuItem key='multi' value={'multi'} primaryText="Multi"/>,
    <MenuItem key='nat_resources' value={'nat_resources'} primaryText="Natural Resources"/>,
    <MenuItem key='parks_rec' value={'parks_rec'} primaryText="Parks & Rec"/>,
    <MenuItem key='phil_religion' value={'phil_religion'} primaryText="Philosophy & Religious"/>,
    <MenuItem key='phys_sci' value={'phys_sci'} primaryText="Physiological Science"/>,
    <MenuItem key='precision_prod' value={'precision_prod'} primaryText="Linguistics"/>,
    <MenuItem key='psych' value={'psych'} primaryText="Psychology"/>,
    <MenuItem key='pub_adm_soc_serv' value={'pub_adm_soc_serv'} primaryText="Social Services"/>,
    <MenuItem key='sci_tech' value={'sci_tech'} primaryText="Science & Technology"/>,
    <MenuItem key='soc_sci' value={'soc_sci'} primaryText="Social Science"/>,
    <MenuItem key='theology' value={'theology'} primaryText="Theology"/>,
    <MenuItem key='transportation' value={'transportation'} primaryText="Transportation"/>,
    <MenuItem key='vis_perf_arts' value={'vis_perf_arts'} primaryText="Visual and Performing Arts"/>
]
